"""Add description to meeting room

Revision ID: 079eadd39fea
Revises: 36f20d1c51f1
Create Date: 2024-10-06 12:28:47.828940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079eadd39fea'
down_revision = '36f20d1c51f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
